// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrleansExercise.Database;

namespace OrleansExercise.Migrations
{
    [DbContext(typeof(OrleansDbContext))]
    [Migration("20210929084858_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrleansExercise.Database.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca7f0fc5-97c6-4b2c-809a-dba2dea629e4"),
                            Address = "Gradacacka 13",
                            FirstName = "Eldor",
                            LastName = "Mujkic",
                            Phone = "+387 61 764 891"
                        },
                        new
                        {
                            Id = new Guid("1166210b-06e6-459b-81ef-49ea0ff2e021"),
                            Address = "Gradacacka 13",
                            FirstName = "Edo",
                            LastName = "Mujkic",
                            Phone = "+387 61 764 891"
                        },
                        new
                        {
                            Id = new Guid("6b0cbae4-4d43-4cb0-aec5-a259640478c1"),
                            Address = "Gradacacka 13",
                            FirstName = "Faris",
                            LastName = "Mujkic",
                            Phone = "+387 61 764 891"
                        },
                        new
                        {
                            Id = new Guid("37cb4f57-4066-46ef-9229-06880ea70bea"),
                            Address = "Gradacacka 13",
                            FirstName = "Kenan",
                            LastName = "Mujkic",
                            Phone = "+387 61 764 891"
                        },
                        new
                        {
                            Id = new Guid("9cab3c3e-e793-4e5a-9460-732e2f2a68f9"),
                            Address = "Gradacacka 13",
                            FirstName = "Admir",
                            LastName = "Mujkic",
                            Phone = "+387 61 764 891"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
